dchat: commit erroring code
error: failed to select a version for darkfi.

... required by package dchat v0.4.1 (/home/x/src/darkfi/example/dchat)

versions that meet the requirements * are: 0.4.1

the package dchat depends on darkfi, with features: async_daemonize but darkfi does not have these features.

failed to select a version for darkfi which could resolve this conflict